[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "public"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://valantinefinder.netlify.app"
    Access-Control-Allow-Methods = "POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

[[headers]]
  for = "/netlify/functions/submit"
  [headers.values]
    Access-Control-Allow-Origin = "https://valantinefinder.netlify.app"
    Access-Control-Allow-Methods = "POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true