[build]
  base = "/"
  command = "npm run build"
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  CI = "true"  # Set CI environment variable for the build process

[context.production.environment]
  NODE_ENV = "production"