[build]
  base = "/"
  command: CI= npm run build
  publish = "public"  # The directory where the built files will be output (adjust if needed)
  functions = "netlify/functions"  # If you are using serverless functions, this is the directory

[context.production.environment]
  NODE_ENV = "production"